export const RBACPaths = {
  account: [
    'delete',
    'fix_email',
    'logout',
    'read',
    'read_bets',
    'read_cashOptions',
    'read_deposits',
    'read_disableBetGoal',
    'read_fasttrackEmails',
    'read_howie_deal',
    'read_lock',
    'read_promoBanned',
    'read_riskCheck',
    'read_stats',
    'read_surveys',
    'read_tips',
    'read_transactions',
    'read_withdrawalLimit',
    'read_withdrawals',
    'send_verify_email',
    'update_2fa',
    'update_affiliate_cut',
    'update_affiliate_id',
    'update_bet_goal',
    'update_bets',
    'update_bulk',
    'update_cashOptions',
    'update_chat',
    'update_deposits',
    'update_dept',
    'update_disableBetGoal',
    'update_email',
    'update_fasttrackEmails',
    'update_howie_deal',
    'update_lock',
    'update_login_attempts',
    'update_manager',
    'update_name',
    'update_permissions',
    'update_product',
    'update_promoBanned',
    'update_promo_banned',
    'update_riskCheck',
    'update_risk_check',
    'update_role',
    'update_stats',
    'update_surveys',
    'update_tips',
    'update_transactions',
    'update_withdrawalLimit',
    'update_withdrawal_limit',
    'update_withdrawals',
  ],
  address_lookup: ['read'],
  balances: ['add', 'mktg', 'reset', 'vip', 'vip_bulk'],
  banner: ['update'],
  bets: ['export', 'read'],
  calldev: ['create'],
  chat: ['delete', 'update', 'read'],
  content: ['create', 'read', 'update'],
  crm: ['create', 'read', 'update', 'delete'],
  crypto_staking: ['update'],
  deposit_bonus: ['create', 'create_bulk', 'update'],
  deposits: ['dangerously_update', 'read', 'update'],
  feature_flags: ['read_alpha'],
  freespins: ['create', 'create_bulk', 'delete', 'read'],
  global_stats: ['read'],
  inventory: ['create', 'delete', 'read', 'update'],
  ipban: ['read', 'update'],
  iplookup: ['read'],
  koth: ['create', 'delete', 'read', 'update'],
  kyc: ['delete', 'read', 'update'],
  legal: ['create', 'delete', 'read', 'update'],
  messaging: ['create', 'delete', 'read', 'update'],
  promos: ['create', 'create_bulk', 'delete', 'read', 'update'],
  raffles: ['create', 'delete', 'read', 'update'],
  rains: ['create', 'manage', 'read'],
  refresh: ['update'],
  reports: ['create', 'read'],
  roowards: ['read', 'update'],
  roowards_recharge: ['read', 'update'],
  settings: ['update'],
  slot_potato: ['create', 'delete', 'read', 'update'],
  sponsors: ['read'],
  stats: ['read'],
  test: ['create', 'delete', 'read', 'update'],
  toggles: ['update'],
  tpgame_disables: ['create', 'delete', 'read'],
  tpgames: ['read', 'update', 'update_bulk'],
  tpgametags: ['create', 'delete', 'read', 'update'],
  user_notes: ['create', 'create_bulk', 'delete', 'read', 'update'],
  user_roles: ['create', 'delete', 'read', 'update'],
  withdrawals: ['read', 'read_flagged', 'update', 'update_flagged'],
} as const

export type RBACResource = keyof typeof RBACPaths
export type RBACAction<T extends RBACResource> = (typeof RBACPaths)[T][number]

export type RBACRequest<T extends RBACResource> = T extends RBACResource
  ? Readonly<{ resource: T; action: (typeof RBACPaths)[T][number] }>
  : never

export type RBACRequests = Readonly<Array<RBACRequest<RBACResource>>>

export type RBACRule = keyof {
  [K in RBACResource as `${K}:${RBACAction<K>}` | `${K}:*` | `*:*`]: true
}
