import { queryFields } from './queryFields'
import { types, unionTypes } from './types'
import { mutationFields } from './mutationFields'
import { subscriptionFields } from './subscriptionFields'

export const AdminGraph = [
  // Types.
  types.ArchivedInventoryItemType,
  types.BetActivityType,
  types.BlockioCurrentBlockType,
  types.BonusCodeType,
  types.BonusCodeTypeSettingsInputType,
  types.BonusCodeTypeType,
  types.CMSContentType,
  types.FreeSpinGameType,
  types.FreeSpinsBuffType,
  types.FreeSpinsTypeSettingsType,
  types.GameTagType,
  types.HouseInventoryItemType,
  types.ItemBuffInputType,
  types.ItemRewardType,
  types.ItemUsageInputType,
  types.KYCRecordType,
  types.MessageDetailedType,
  types.MessageTemplateType,
  types.MessageType,
  types.QuestTemplateType,
  types.QuestType,
  types.RaffleEntryType,
  types.RaffleType,
  types.RBACPolicyType,
  types.RBACRoleType,
  types.RippleDestinationTagType,
  types.SlotPotatoType,
  types.TPGameAdminType,
  types.TPGameAggregatorType,
  types.TPGameBlockType,
  types.TPGameMetadataType,
  types.TPGamesAdminGetPaginatedResponseType,
  types.TPGamesFilterType,
  types.TronUserWalletType,
  types.UserInventoryItemType,
  types.RakeboostType,
  types.UserType,
  types.WithdrawalType,

  // Union Types.
  unionTypes.BonusCodeTypeSettingsType,
  unionTypes.EmoteBuffSettingsType,
  unionTypes.FreeBetBuffSettingsType,
  unionTypes.FreeSpinsBuffSettingsType,
  unionTypes.ItemBuffSettingsType,
  unionTypes.ItemBuffSettingsType,
  unionTypes.ItemBuffType,
  unionTypes.NewPlayerIncentiveQuestSettingsType,
  unionTypes.PageViewQuestSettingsType,
  unionTypes.QuestCriteriaSettingsType,
  unionTypes.RoowardsBuffSettingsType,

  // Root Query Fields.
  queryFields.BetActivityQueryField,
  queryFields.BlockioCurrentBlockQueryField,
  queryFields.BonusCodeByIdQueryField,
  queryFields.BonusCodesQueryField,
  queryFields.CMSContentQueryField,
  queryFields.FlaggedWithdrawalsQueryField,
  queryFields.GameTagsNotCachedQueryField,
  queryFields.HouseInventoryQueryField,
  queryFields.InventoryItemRewardsQueryField,
  queryFields.MessageQueryField,
  queryFields.MessagesQueryField,
  queryFields.MessageTemplateQueryField,
  queryFields.MessageTemplatesQueryField,
  queryFields.QuestsACPQueryField,
  queryFields.QuestTemplatesQueryField,
  queryFields.RaffleQueryField,
  queryFields.RBACPoliciesQueryField,
  queryFields.RBACRolesQueryField,
  queryFields.SlotPotatoQueryField,
  queryFields.TPGameAdminQueryField,
  queryFields.TPGameBlockQueryField,
  queryFields.TPGameMetadataQueryField,
  queryFields.TPGamesAdminGetPaginatedQueryField,
  queryFields.TPGamesAdminQueryField,
  queryFields.TPGamesByAggregatorQueryField,
  queryFields.TPGamesGetAllQueryField,
  queryFields.TPGamesProviderNamesQueryField,
  queryFields.UserInventoryQueryField,
  queryFields.UserQueryField,
  queryFields.UsersQueryField,

  // Root Mutation Fields.
  mutationFields.BlockioTransactionUpdateMutationField,
  mutationFields.BonusCodeCreateMutationField,
  mutationFields.BonusCodeDeleteMutationField,
  mutationFields.BonusCodeUpdateMutationField,
  mutationFields.FlaggedWithdrawalApproveMutationField,
  mutationFields.FlaggedWithdrawalRejectMutationField,
  mutationFields.GameTagCreateMutationField,
  mutationFields.GameTagDeleteMutationField,
  mutationFields.GameTagReorderMutationField,
  mutationFields.GameTagUpdateMutationField,
  mutationFields.InventoryItemCreateMutationField,
  mutationFields.InventoryItemRewardClaimMutationField,
  mutationFields.InventoryItemRewardCreateMutationField,
  mutationFields.InventoryItemsAddToUserMutationField,
  mutationFields.InventoryItemsRemoveFromUserMutationField,
  mutationFields.InventoryItemsTransferMutationField,
  mutationFields.InventoryItemUpdateMutationField,
  mutationFields.MessageCreateMutationField,
  mutationFields.MessageDeleteMutationField,
  mutationFields.MessageRestoreMutationField,
  mutationFields.MessageSendMutationField,
  mutationFields.MessageTemplateCreateMutationField,
  mutationFields.MessageTemplateDeleteMutationField,
  mutationFields.MessageTemplateRestoreMutationField,
  mutationFields.MessageTemplateUpdateMutationField,
  mutationFields.MessageUpdateMutationField,
  mutationFields.QuestCreateFromTemplateMutationField,
  mutationFields.QuestTemplateCreateMutationField,
  mutationFields.RaffleRedrawWinnerMutationField,
  mutationFields.RaffleTicketsCreditMutationField,
  mutationFields.RBACPolicyCreateMutationField,
  mutationFields.RBACPolicyDeleteMutationField,
  mutationFields.RBACPolicyUpdateMutationField,
  mutationFields.RBACRoleCreateMutationField,
  mutationFields.RBACRoleUpdateMutationField,
  mutationFields.RoleDeleteMutationField,
  mutationFields.SlotPotatoCreateMutationField,
  mutationFields.SlotPotatoDisableMutationField,
  mutationFields.SlotPotatoEnableMutationField,
  mutationFields.SlotPotatoUpdateMutationField,
  mutationFields.TPGameBlockMutationField,
  mutationFields.TPGameCategoryUpdateMutationField,
  mutationFields.TPGameEnableMutationField,
  mutationFields.TPGameUpdateApprovalStatusMutationField,
  mutationFields.TPGameUpdateMutationField,
  mutationFields.UserResetKYCLevelMutationField,
  mutationFields.UserUpdateRBACRolesMutationField,

  // Root Subscription Fields.
  subscriptionFields.FlaggedWithdrawalCreatedSubscriptionField,
]
