export enum CountryCodeEnum {
  UnitedStates = 'US',
  Afghanistan = 'AF',
  AlandIslands = 'AX',
  Albania = 'AL',
  Algeria = 'DZ',
  AmericanSamoa = 'AS',
  Andorra = 'AD',
  Angola = 'AO',
  Anguilla = 'AI',
  Antarctica = 'AQ',
  AntiguaAndBarbuda = 'AG',
  Argentina = 'AR',
  Armenia = 'AM',
  Aruba = 'AW',
  Australia = 'AU',
  Austria = 'AT',
  Azerbaijan = 'AZ',
  Bahamas = 'BS',
  Bahrain = 'BH',
  Bangladesh = 'BD',
  Barbados = 'BB',
  Belarus = 'BY',
  Belgium = 'BE',
  Belize = 'BZ',
  Benin = 'BJ',
  Bermuda = 'BM',
  Bhutan = 'BT',
  Bolivia = 'BO',
  BonaireSintEustatiusSaba = 'BQ',
  BosniaAndHerzegovina = 'BA',
  Botswana = 'BW',
  BouvetIsland = 'BV',
  Brazil = 'BR',
  BritishIndianOceanTerritory = 'IO',
  BruneiDarussalam = 'BN',
  Bulgaria = 'BG',
  BurkinaFaso = 'BF',
  Burundi = 'BI',
  Cambodia = 'KH',
  Cameroon = 'CM',
  Canada = 'CA',
  CapeVerde = 'CV',
  CaymanIslands = 'KY',
  CentralAfricanRepublic = 'CF',
  Chad = 'TD',
  Chile = 'CL',
  China = 'CN',
  ChristmasIsland = 'CX',
  CocosKeelingIslands = 'CC',
  Colombia = 'CO',
  Comoros = 'KM',
  Congo = 'CG',
  CongoDemocraticRepublic = 'CD',
  CookIslands = 'CK',
  CostaRica = 'CR',
  CoteDIvoire = 'CI',
  Croatia = 'HR',
  Cuba = 'CU',
  Curaçao = 'CW',
  Cyprus = 'CY',
  CzechRepublic = 'CZ',
  Denmark = 'DK',
  Djibouti = 'DJ',
  Dominica = 'DM',
  DominicanRepublic = 'DO',
  Ecuador = 'EC',
  Egypt = 'EG',
  ElSalvador = 'SV',
  EquatorialGuinea = 'GQ',
  Eritrea = 'ER',
  Estonia = 'EE',
  Ethiopia = 'ET',
  FalklandIslands = 'FK',
  FaroeIslands = 'FO',
  Fiji = 'FJ',
  Finland = 'FI',
  France = 'FR',
  FrenchGuiana = 'GF',
  FrenchPolynesia = 'PF',
  FrenchSouthernTerritories = 'TF',
  Gabon = 'GA',
  Gambia = 'GM',
  Georgia = 'GE',
  Germany = 'DE',
  Ghana = 'GH',
  Gibraltar = 'GI',
  Greece = 'GR',
  Greenland = 'GL',
  Grenada = 'GD',
  Guadeloupe = 'GP',
  Guam = 'GU',
  Guatemala = 'GT',
  Guernsey = 'GG',
  Guinea = 'GN',
  GuineaBissau = 'GW',
  Guyana = 'GY',
  Haiti = 'HT',
  HeardIslandMcdonaldIslands = 'HM',
  HolySeeVaticanCityState = 'VA',
  Honduras = 'HN',
  HongKong = 'HK',
  Hungary = 'HU',
  Iceland = 'IS',
  India = 'IN',
  Indonesia = 'ID',
  Iran = 'IR',
  Iraq = 'IQ',
  Ireland = 'IE',
  IsleOfMan = 'IM',
  Israel = 'IL',
  Italy = 'IT',
  Jamaica = 'JM',
  Japan = 'JP',
  Jersey = 'JE',
  Jordan = 'JO',
  Kazakhstan = 'KZ',
  Kenya = 'KE',
  Kiribati = 'KI',
  Korea = 'KR',
  KoreaDemocraticPeoplesRepublic = 'KP',
  Kuwait = 'KW',
  Kyrgyzstan = 'KG',
  LaoPeoplesDemocraticRepublic = 'LA',
  Latvia = 'LV',
  Lebanon = 'LB',
  Lesotho = 'LS',
  Liberia = 'LR',
  LibyanArabJamahiriya = 'LY',
  Liechtenstein = 'LI',
  Lithuania = 'LT',
  Luxembourg = 'LU',
  Macao = 'MO',
  Macedonia = 'MK',
  Madagascar = 'MG',
  Malawi = 'MW',
  Malaysia = 'MY',
  Maldives = 'MV',
  Mali = 'ML',
  Malta = 'MT',
  MarshallIslands = 'MH',
  Martinique = 'MQ',
  Mauritania = 'MR',
  Mauritius = 'MU',
  Mayotte = 'YT',
  Mexico = 'MX',
  Micronesia = 'FM',
  Moldova = 'MD',
  Monaco = 'MC',
  Mongolia = 'MN',
  Montenegro = 'ME',
  Montserrat = 'MS',
  Morocco = 'MA',
  Mozambique = 'MZ',
  Myanmar = 'MM',
  Namibia = 'NA',
  Nauru = 'NR',
  Nepal = 'NP',
  Netherlands = 'NL',
  NewCaledonia = 'NC',
  NewZealand = 'NZ',
  Nicaragua = 'NI',
  Niger = 'NE',
  Nigeria = 'NG',
  Niue = 'NU',
  NorfolkIsland = 'NF',
  NorthernMarianaIslands = 'MP',
  Norway = 'NO',
  Oman = 'OM',
  Pakistan = 'PK',
  Palau = 'PW',
  PalestinianTerritory = 'PS',
  Panama = 'PA',
  PapuaNewGuinea = 'PG',
  Paraguay = 'PY',
  Peru = 'PE',
  Philippines = 'PH',
  Pitcairn = 'PN',
  Poland = 'PL',
  Portugal = 'PT',
  PuertoRico = 'PR',
  Qatar = 'QA',
  Reunion = 'RE',
  Romania = 'RO',
  RussianFederation = 'RU',
  Rwanda = 'RW',
  SaintBarthelemy = 'BL',
  SaintHelena = 'SH',
  SaintKittsAndNevis = 'KN',
  SaintLucia = 'LC',
  SaintMartin = 'MF',
  SaintPierreAndMiquelon = 'PM',
  SaintVincentAndGrenadines = 'VC',
  Samoa = 'WS',
  SanMarino = 'SM',
  SaoTomeAndPrincipe = 'ST',
  SaudiArabia = 'SA',
  Senegal = 'SN',
  Serbia = 'RS',
  Seychelles = 'SC',
  SierraLeone = 'SL',
  Singapore = 'SG',
  SintMaarten = 'SX',
  Slovakia = 'SK',
  Slovenia = 'SI',
  SolomonIslands = 'SB',
  Somalia = 'SO',
  SouthAfrica = 'ZA',
  SouthGeorgiaAndSandwichIsl = 'GS',
  SouthSudan = 'SS',
  Spain = 'ES',
  SriLanka = 'LK',
  Sudan = 'SD',
  Suriname = 'SR',
  SvalbardAndJanMayen = 'SJ',
  Swaziland = 'SZ',
  Sweden = 'SE',
  Switzerland = 'CH',
  SyrianArabRepublic = 'SY',
  Taiwan = 'TW',
  Tajikistan = 'TJ',
  Tanzania = 'TZ',
  Thailand = 'TH',
  TimorLeste = 'TL',
  Togo = 'TG',
  Tokelau = 'TK',
  Tonga = 'TO',
  TrinidadAndTobago = 'TT',
  Tunisia = 'TN',
  Turkey = 'TR',
  Turkmenistan = 'TM',
  TurksAndCaicosIslands = 'TC',
  Tuvalu = 'TV',
  Uganda = 'UG',
  Ukraine = 'UA',
  UnitedArabEmirates = 'AE',
  UnitedKingdom = 'GB',
  UnitedStatesOutlyingIslands = 'UM',
  Uruguay = 'UY',
  Uzbekistan = 'UZ',
  Vanuatu = 'VU',
  Venezuela = 'VE',
  VietNam = 'VN',
  VirginIslandsBritish = 'VG',
  VirginIslandsUS = 'VI',
  WallisAndFutuna = 'WF',
  WesternSahara = 'EH',
  Yemen = 'YE',
  Zambia = 'ZM',
  Zimbabwe = 'ZW',
}

export type CountryName = keyof typeof CountryCodeEnum

// TODO map to enum values so the enum is one source of truth
export const CountryCodeMap: Record<CountryCodeEnum, string> = {
  [CountryCodeEnum.UnitedStates]: 'US',
  [CountryCodeEnum.Afghanistan]: 'AF',
  [CountryCodeEnum.AlandIslands]: 'AX',
  [CountryCodeEnum.Albania]: 'AL',
  [CountryCodeEnum.Algeria]: 'DZ',
  [CountryCodeEnum.AmericanSamoa]: 'AS',
  [CountryCodeEnum.Andorra]: 'AD',
  [CountryCodeEnum.Angola]: 'AO',
  [CountryCodeEnum.Anguilla]: 'AI',
  [CountryCodeEnum.Antarctica]: 'AQ',
  [CountryCodeEnum.AntiguaAndBarbuda]: 'AG',
  [CountryCodeEnum.Argentina]: 'AR',
  [CountryCodeEnum.Armenia]: 'AM',
  [CountryCodeEnum.Aruba]: 'AW',
  [CountryCodeEnum.Australia]: 'AU',
  [CountryCodeEnum.Austria]: 'AT',
  [CountryCodeEnum.Azerbaijan]: 'AZ',
  [CountryCodeEnum.Bahamas]: 'BS',
  [CountryCodeEnum.Bahrain]: 'BH',
  [CountryCodeEnum.Bangladesh]: 'BD',
  [CountryCodeEnum.Barbados]: 'BB',
  [CountryCodeEnum.Belarus]: 'BY',
  [CountryCodeEnum.Belgium]: 'BE',
  [CountryCodeEnum.Belize]: 'BZ',
  [CountryCodeEnum.Benin]: 'BJ',
  [CountryCodeEnum.Bermuda]: 'BM',
  [CountryCodeEnum.Bhutan]: 'BT',
  [CountryCodeEnum.Bolivia]: 'BO',
  [CountryCodeEnum.BonaireSintEustatiusSaba]: 'BQ',
  [CountryCodeEnum.BosniaAndHerzegovina]: 'BA',
  [CountryCodeEnum.Botswana]: 'BW',
  [CountryCodeEnum.BouvetIsland]: 'BV',
  [CountryCodeEnum.Brazil]: 'BR',
  [CountryCodeEnum.BritishIndianOceanTerritory]: 'IO',
  [CountryCodeEnum.BruneiDarussalam]: 'BN',
  [CountryCodeEnum.Bulgaria]: 'BG',
  [CountryCodeEnum.BurkinaFaso]: 'BF',
  [CountryCodeEnum.Burundi]: 'BI',
  [CountryCodeEnum.Cambodia]: 'KH',
  [CountryCodeEnum.Cameroon]: 'CM',
  [CountryCodeEnum.Canada]: 'CA',
  [CountryCodeEnum.CapeVerde]: 'CV',
  [CountryCodeEnum.CaymanIslands]: 'KY',
  [CountryCodeEnum.CentralAfricanRepublic]: 'CF',
  [CountryCodeEnum.Chad]: 'TD',
  [CountryCodeEnum.Chile]: 'CL',
  [CountryCodeEnum.China]: 'CN',
  [CountryCodeEnum.ChristmasIsland]: 'CX',
  [CountryCodeEnum.CocosKeelingIslands]: 'CC',
  [CountryCodeEnum.Colombia]: 'CO',
  [CountryCodeEnum.Comoros]: 'KM',
  [CountryCodeEnum.Congo]: 'CG',
  [CountryCodeEnum.CongoDemocraticRepublic]: 'CD',
  [CountryCodeEnum.CookIslands]: 'CK',
  [CountryCodeEnum.CostaRica]: 'CR',
  [CountryCodeEnum.CoteDIvoire]: 'CI',
  [CountryCodeEnum.Croatia]: 'HR',
  [CountryCodeEnum.Cuba]: 'CU',
  [CountryCodeEnum.Curaçao]: 'CW',
  [CountryCodeEnum.Cyprus]: 'CY',
  [CountryCodeEnum.CzechRepublic]: 'CZ',
  [CountryCodeEnum.Denmark]: 'DK',
  [CountryCodeEnum.Djibouti]: 'DJ',
  [CountryCodeEnum.Dominica]: 'DM',
  [CountryCodeEnum.DominicanRepublic]: 'DO',
  [CountryCodeEnum.Ecuador]: 'EC',
  [CountryCodeEnum.Egypt]: 'EG',
  [CountryCodeEnum.ElSalvador]: 'SV',
  [CountryCodeEnum.EquatorialGuinea]: 'GQ',
  [CountryCodeEnum.Eritrea]: 'ER',
  [CountryCodeEnum.Estonia]: 'EE',
  [CountryCodeEnum.Ethiopia]: 'ET',
  [CountryCodeEnum.FalklandIslands]: 'FK',
  [CountryCodeEnum.FaroeIslands]: 'FO',
  [CountryCodeEnum.Fiji]: 'FJ',
  [CountryCodeEnum.Finland]: 'FI',
  [CountryCodeEnum.France]: 'FR',
  [CountryCodeEnum.FrenchGuiana]: 'GF',
  [CountryCodeEnum.FrenchPolynesia]: 'PF',
  [CountryCodeEnum.FrenchSouthernTerritories]: 'TF',
  [CountryCodeEnum.Gabon]: 'GA',
  [CountryCodeEnum.Gambia]: 'GM',
  [CountryCodeEnum.Georgia]: 'GE',
  [CountryCodeEnum.Germany]: 'DE',
  [CountryCodeEnum.Ghana]: 'GH',
  [CountryCodeEnum.Gibraltar]: 'GI',
  [CountryCodeEnum.Greece]: 'GR',
  [CountryCodeEnum.Greenland]: 'GL',
  [CountryCodeEnum.Grenada]: 'GD',
  [CountryCodeEnum.Guadeloupe]: 'GP',
  [CountryCodeEnum.Guam]: 'GU',
  [CountryCodeEnum.Guatemala]: 'GT',
  [CountryCodeEnum.Guernsey]: 'GG',
  [CountryCodeEnum.Guinea]: 'GN',
  [CountryCodeEnum.GuineaBissau]: 'GW',
  [CountryCodeEnum.Guyana]: 'GY',
  [CountryCodeEnum.Haiti]: 'HT',
  [CountryCodeEnum.HeardIslandMcdonaldIslands]: 'HM',
  [CountryCodeEnum.HolySeeVaticanCityState]: 'VA',
  [CountryCodeEnum.Honduras]: 'HN',
  [CountryCodeEnum.HongKong]: 'HK',
  [CountryCodeEnum.Hungary]: 'HU',
  [CountryCodeEnum.Iceland]: 'IS',
  [CountryCodeEnum.India]: 'IN',
  [CountryCodeEnum.Indonesia]: 'ID',
  [CountryCodeEnum.Iran]: 'IR',
  [CountryCodeEnum.Iraq]: 'IQ',
  [CountryCodeEnum.Ireland]: 'IE',
  [CountryCodeEnum.IsleOfMan]: 'IM',
  [CountryCodeEnum.Israel]: 'IL',
  [CountryCodeEnum.Italy]: 'IT',
  [CountryCodeEnum.Jamaica]: 'JM',
  [CountryCodeEnum.Japan]: 'JP',
  [CountryCodeEnum.Jersey]: 'JE',
  [CountryCodeEnum.Jordan]: 'JO',
  [CountryCodeEnum.Kazakhstan]: 'KZ',
  [CountryCodeEnum.Kenya]: 'KE',
  [CountryCodeEnum.Kiribati]: 'KI',
  [CountryCodeEnum.Korea]: 'KR',
  [CountryCodeEnum.KoreaDemocraticPeoplesRepublic]: 'KP',
  [CountryCodeEnum.Kuwait]: 'KW',
  [CountryCodeEnum.Kyrgyzstan]: 'KG',
  [CountryCodeEnum.LaoPeoplesDemocraticRepublic]: 'LA',
  [CountryCodeEnum.Latvia]: 'LV',
  [CountryCodeEnum.Lebanon]: 'LB',
  [CountryCodeEnum.Lesotho]: 'LS',
  [CountryCodeEnum.Liberia]: 'LR',
  [CountryCodeEnum.LibyanArabJamahiriya]: 'LY',
  [CountryCodeEnum.Liechtenstein]: 'LI',
  [CountryCodeEnum.Lithuania]: 'LT',
  [CountryCodeEnum.Luxembourg]: 'LU',
  [CountryCodeEnum.Macao]: 'MO',
  [CountryCodeEnum.Macedonia]: 'MK',
  [CountryCodeEnum.Madagascar]: 'MG',
  [CountryCodeEnum.Malawi]: 'MW',
  [CountryCodeEnum.Malaysia]: 'MY',
  [CountryCodeEnum.Maldives]: 'MV',
  [CountryCodeEnum.Mali]: 'ML',
  [CountryCodeEnum.Malta]: 'MT',
  [CountryCodeEnum.MarshallIslands]: 'MH',
  [CountryCodeEnum.Martinique]: 'MQ',
  [CountryCodeEnum.Mauritania]: 'MR',
  [CountryCodeEnum.Mauritius]: 'MU',
  [CountryCodeEnum.Mayotte]: 'YT',
  [CountryCodeEnum.Mexico]: 'MX',
  [CountryCodeEnum.Micronesia]: 'FM',
  [CountryCodeEnum.Moldova]: 'MD',
  [CountryCodeEnum.Monaco]: 'MC',
  [CountryCodeEnum.Mongolia]: 'MN',
  [CountryCodeEnum.Montenegro]: 'ME',
  [CountryCodeEnum.Montserrat]: 'MS',
  [CountryCodeEnum.Morocco]: 'MA',
  [CountryCodeEnum.Mozambique]: 'MZ',
  [CountryCodeEnum.Myanmar]: 'MM',
  [CountryCodeEnum.Namibia]: 'NA',
  [CountryCodeEnum.Nauru]: 'NR',
  [CountryCodeEnum.Nepal]: 'NP',
  [CountryCodeEnum.Netherlands]: 'NL',
  [CountryCodeEnum.NewCaledonia]: 'NC',
  [CountryCodeEnum.NewZealand]: 'NZ',
  [CountryCodeEnum.Nicaragua]: 'NI',
  [CountryCodeEnum.Niger]: 'NE',
  [CountryCodeEnum.Nigeria]: 'NG',
  [CountryCodeEnum.Niue]: 'NU',
  [CountryCodeEnum.NorfolkIsland]: 'NF',
  [CountryCodeEnum.NorthernMarianaIslands]: 'MP',
  [CountryCodeEnum.Norway]: 'NO',
  [CountryCodeEnum.Oman]: 'OM',
  [CountryCodeEnum.Pakistan]: 'PK',
  [CountryCodeEnum.Palau]: 'PW',
  [CountryCodeEnum.PalestinianTerritory]: 'PS',
  [CountryCodeEnum.Panama]: 'PA',
  [CountryCodeEnum.PapuaNewGuinea]: 'PG',
  [CountryCodeEnum.Paraguay]: 'PY',
  [CountryCodeEnum.Peru]: 'PE',
  [CountryCodeEnum.Philippines]: 'PH',
  [CountryCodeEnum.Pitcairn]: 'PN',
  [CountryCodeEnum.Poland]: 'PL',
  [CountryCodeEnum.Portugal]: 'PT',
  [CountryCodeEnum.PuertoRico]: 'PR',
  [CountryCodeEnum.Qatar]: 'QA',
  [CountryCodeEnum.Reunion]: 'RE',
  [CountryCodeEnum.Romania]: 'RO',
  [CountryCodeEnum.RussianFederation]: 'RU',
  [CountryCodeEnum.Rwanda]: 'RW',
  [CountryCodeEnum.SaintBarthelemy]: 'BL',
  [CountryCodeEnum.SaintHelena]: 'SH',
  [CountryCodeEnum.SaintKittsAndNevis]: 'KN',
  [CountryCodeEnum.SaintLucia]: 'LC',
  [CountryCodeEnum.SaintMartin]: 'MF',
  [CountryCodeEnum.SaintPierreAndMiquelon]: 'PM',
  [CountryCodeEnum.SaintVincentAndGrenadines]: 'VC',
  [CountryCodeEnum.Samoa]: 'WS',
  [CountryCodeEnum.SanMarino]: 'SM',
  [CountryCodeEnum.SaoTomeAndPrincipe]: 'ST',
  [CountryCodeEnum.SaudiArabia]: 'SA',
  [CountryCodeEnum.Senegal]: 'SN',
  [CountryCodeEnum.Serbia]: 'RS',
  [CountryCodeEnum.Seychelles]: 'SC',
  [CountryCodeEnum.SierraLeone]: 'SL',
  [CountryCodeEnum.Singapore]: 'SG',
  [CountryCodeEnum.SintMaarten]: 'SX',
  [CountryCodeEnum.Slovakia]: 'SK',
  [CountryCodeEnum.Slovenia]: 'SI',
  [CountryCodeEnum.SolomonIslands]: 'SB',
  [CountryCodeEnum.Somalia]: 'SO',
  [CountryCodeEnum.SouthAfrica]: 'ZA',
  [CountryCodeEnum.SouthGeorgiaAndSandwichIsl]: 'GS',
  [CountryCodeEnum.SouthSudan]: 'SS',
  [CountryCodeEnum.Spain]: 'ES',
  [CountryCodeEnum.SriLanka]: 'LK',
  [CountryCodeEnum.Sudan]: 'SD',
  [CountryCodeEnum.Suriname]: 'SR',
  [CountryCodeEnum.SvalbardAndJanMayen]: 'SJ',
  [CountryCodeEnum.Swaziland]: 'SZ',
  [CountryCodeEnum.Sweden]: 'SE',
  [CountryCodeEnum.Switzerland]: 'CH',
  [CountryCodeEnum.SyrianArabRepublic]: 'SY',
  [CountryCodeEnum.Taiwan]: 'TW',
  [CountryCodeEnum.Tajikistan]: 'TJ',
  [CountryCodeEnum.Tanzania]: 'TZ',
  [CountryCodeEnum.Thailand]: 'TH',
  [CountryCodeEnum.TimorLeste]: 'TL',
  [CountryCodeEnum.Togo]: 'TG',
  [CountryCodeEnum.Tokelau]: 'TK',
  [CountryCodeEnum.Tonga]: 'TO',
  [CountryCodeEnum.TrinidadAndTobago]: 'TT',
  [CountryCodeEnum.Tunisia]: 'TN',
  [CountryCodeEnum.Turkey]: 'TR',
  [CountryCodeEnum.Turkmenistan]: 'TM',
  [CountryCodeEnum.TurksAndCaicosIslands]: 'TC',
  [CountryCodeEnum.Tuvalu]: 'TV',
  [CountryCodeEnum.Uganda]: 'UG',
  [CountryCodeEnum.Ukraine]: 'UA',
  [CountryCodeEnum.UnitedArabEmirates]: 'AE',
  [CountryCodeEnum.UnitedKingdom]: 'GB',
  [CountryCodeEnum.UnitedStatesOutlyingIslands]: 'UM',
  [CountryCodeEnum.Uruguay]: 'UY',
  [CountryCodeEnum.Uzbekistan]: 'UZ',
  [CountryCodeEnum.Vanuatu]: 'VU',
  [CountryCodeEnum.Venezuela]: 'VE',
  [CountryCodeEnum.VietNam]: 'VN',
  [CountryCodeEnum.VirginIslandsBritish]: 'VG',
  [CountryCodeEnum.VirginIslandsUS]: 'VI',
  [CountryCodeEnum.WallisAndFutuna]: 'WF',
  [CountryCodeEnum.WesternSahara]: 'EH',
  [CountryCodeEnum.Yemen]: 'YE',
  [CountryCodeEnum.Zambia]: 'ZM',
  [CountryCodeEnum.Zimbabwe]: 'ZW',
}
