name: Validate Asset Sizes
description: Validates that changed assets are below file size limits.

runs:
  using: composite
  steps:
    - name: Fetch necessary refs
      shell: bash
      run: |
        git fetch --depth=1 origin ${{ github.event.pull_request.base.ref }}
        git --no-pager log --oneline -n 5
        git --no-pager log --oneline -n 5 origin/${{ github.event.pull_request.base.ref }}

    - name: Run file validator
      shell: bash
      run: |
        files=$(git diff --name-only --diff-filter=AMR origin/${{ github.event.pull_request.base.ref }} ${{ github.sha }})
        ./scripts/validate-filesizes.sh "$files"
