export type { CryptoBalances, BalanceRepresentation } from './defaults'
export { fetchBtcBalances } from './btc'
export { fetchLtcBalances } from './ltc'
export { fetchDogeBalances } from './doge'
export { fetchXrpBalances } from './xrp'
export { fetchTrxBalances } from './trx'
export { fetchEthBalances } from './eth'
export { fetchErc20Balance } from './erc20'
