import { GAME_TAG_FAVORITES_LINK } from 'app/components'
import {
  CASINO_GAME_SHOWS_LINK,
  CASINO_POPULAR_LINK,
  CASINO_ROOBET_GAMES_LINK,
  CASINO_SLOTS_LINK,
} from 'app/routes/CasinoPageRoute'

/**
 * Hub88 provided Hacksaw -> Hacksaw direct integration migration
 * Games we had with both are redirected from old to new. Games we
 * had with Hub88 but not in Hacksaw are redirected to the provider page.
 */
const GAME_REDIRECTS: ReadonlyMap<string, string> = new Map([
  ['/game/hub88\\:hsg_myluckynumber', '/provider/hacksaw-gaming'],
  ['/game/hub88\\:hsg_letitsnow', '/provider/hacksaw-gaming'],
  ['/game/hub88\\:hsg_cubes2', '/provider/hacksaw-gaming'],
  ['/game/hub88\\:hsg_stackem', '/provider/hacksaw-gaming'],
  ['/game/hub88\\:hsg_hopnpop', '/provider/hacksaw-gaming'],
  ['/game/hub88\\:hsg_toshivideoclub', '/provider/hacksaw-gaming'],
  ['/game/hub88\\:hsg_rocketreels', '/provider/hacksaw-gaming'],
  ['/game/hub88\\:hsg_wanteddeadorawild', '/provider/hacksaw-gaming'],
  ['/game/hub88\\:hsg_cashquest', '/provider/hacksaw-gaming'],
  ['/game/hub88\\:hsg_tastytreats', '/provider/hacksaw-gaming'],
  ['/game/hub88\\:hsg_jokerbombs', '/provider/hacksaw-gaming'],
  ['/game/hub88\\:hsg_kingcarrot', '/provider/hacksaw-gaming'],
  ['/game/hub88\\:hsg_spookyscaryscratchy', '/provider/hacksaw-gaming'],
  ['/game/hub88\\:hsg_harvestwilds', '/provider/hacksaw-gaming'],
  ['/game/hub88\\:hsg_stackemscratch', '/provider/hacksaw-gaming'],
  ['/game/hub88\\:hsg_theboweryboys', '/provider/hacksaw-gaming'],
  ['/game/hub88\\:hsg_mines', '/provider/hacksaw-gaming'],
  ['/game/hub88\\:hsg_coins', '/provider/hacksaw-gaming'],
  ['/game/hub88\\:hsg_boxes', '/provider/hacksaw-gaming'],
  ['/game/hub88\\:hsg_handofanubis94', '/provider/hacksaw-gaming'],
  ['/game/hub88\\:hsg_handofanubis92', '/provider/hacksaw-gaming'],
  ['/game/hub88\\:hsg_itero', '/provider/hacksaw-gaming'],
  ['/game/hub88\\:hsg_buffalostacknsync', '/provider/hacksaw-gaming'],
  ['/game/hub88\\:hsg_outlawsinc', '/provider/hacksaw-gaming'],
  ['/game/hub88\\:hsg_born-wild', '/provider/hacksaw-gaming'],
  ['/game/hub88\\:hsg_forestfortune94', '/provider/hacksaw-gaming'],
  ['/game/hub88\\:hsg_alphaeagle94', '/provider/hacksaw-gaming'],
  ['/game/hub88\\:hsg_alphaeagle92', '/provider/hacksaw-gaming'],
  ['/game/hub88\\:hsg_platinumscratch', '/game/hacksaw:1001'],
  ['/game/hub88\\:hsg_goldscratch', '/game/hacksaw:1002'],
  ['/game/hub88\\:hsg_silverscratch', '/game/hacksaw:1003'],
  ['/game/hub88\\:hsg_bronzescratch', '/game/hacksaw:1004'],
  ['/game/hub88\\:hsg_express200', '/game/hacksaw:1006'],
  ['/game/hub88\\:hsg_scratchymini', '/game/hacksaw:1007'],
  ['/game/hub88\\:hsg_scratchy', '/game/hacksaw:1008'],
  ['/game/hub88\\:hsg_scratchybig', '/game/hacksaw:1009'],
  ['/game/hub88\\:hsg_kingtreasure', '/game/hacksaw:1010'],
  ['/game/hub88\\:hsg_queentreasure', '/game/hacksaw:1011'],
  ['/game/hub88\\:hsg_princetreasure', '/game/hacksaw:1013'],
  ['/game/hub88\\:hsg_happyscratch', '/game/hacksaw:1014'],
  ['/game/hub88\\:hsg_luckyscratch', '/game/hacksaw:1016'],
  ['/game/hub88\\:hsg_dreamcarurban', '/game/hacksaw:1017'],
  ['/game/hub88\\:hsg_dreamcarsuv', '/game/hacksaw:1018'],
  ['/game/hub88\\:hsg_dreamcarspeed', '/game/hacksaw:1019'],
  ['/game/hub88\\:hsg_cashvaulti', '/game/hacksaw:1024'],
  ['/game/hub88\\:hsg_cashvaultii', '/game/hacksaw:1025'],
  ['/game/hub88\\:hsg_doublesalary1year', '/game/hacksaw:1034'],
  ['/game/hub88\\:hsg_shavethebeard', '/game/hacksaw:1045'],
  ['/game/hub88\\:hsg_cutthegrass', '/game/hacksaw:1046'],
  ['/game/hub88\\:hsg_scratchem', '/game/hacksaw:1047'],
  ['/game/hub88\\:hsg_goldrush', '/game/hacksaw:1020'],
  ['/game/hub88\\:hsg_rubyrush', '/game/hacksaw:1021'],
  ['/game/hub88\\:hsg_diamondrush', '/game/hacksaw:1022'],
  ['/game/hub88\\:hsg_luckyshot', '/game/hacksaw:1023'],
  ['/game/hub88\\:hsg_luckynumbersx8', '/game/hacksaw:1027'],
  ['/game/hub88\\:hsg_luckynumbersx12', '/game/hacksaw:1028'],
  ['/game/hub88\\:hsg_luckynumbersx16', '/game/hacksaw:1029'],
  ['/game/hub88\\:hsg_luckynumbersx20', '/game/hacksaw:1030'],
  ['/game/hub88\\:hsg_itsbananas', '/game/hacksaw:1031'],
  ['/game/hub88\\:hsg_omnom', '/game/hacksaw:1043'],
  ['/game/hub88\\:hsg_stickem', '/game/hacksaw:1042'],
  ['/game/hub88\\:hsg_miamimultiplier', '/game/hacksaw:1049'],
  ['/game/hub88\\:hsg_cubes', '/game/hacksaw:1048'],
  ['/game/hub88\\:hsg_breaktheice', '/game/hacksaw:1050'],
  ['/game/hub88\\:hsg_frogsscratch', '/game/hacksaw:1051'],
  ['/game/hub88\\:hsg_goldcoins', '/game/hacksaw:1052'],
  ['/game/hub88\\:hsg_koicash', '/game/hacksaw:1053'],
  ['/game/hub88\\:hsg_cashcompass', '/game/hacksaw:1055'],
  ['/game/hub88\\:hsg_cashscratch', '/game/hacksaw:1057'],
  ['/game/hub88\\:hsg_shavethesheep', '/game/hacksaw:1060'],
  ['/game/hub88\\:hsg_balloons', '/game/hacksaw:1061'],
  ['/game/hub88\\:hsg_crazydonuts', '/game/hacksaw:1062'],
  ['/game/hub88\\:hsg_ratriches', '/game/hacksaw:1063'],
  ['/game/hub88\\:hsg_gopanda', '/game/hacksaw:1064'],
  ['/game/hub88\\:hsg_cashpool', '/game/hacksaw:1065'],
  ['/game/hub88\\:hsg_therespinners', '/game/hacksaw:1058'],
  ['/game/hub88\\:hsg_chaoscrew', '/game/hacksaw:1059'],
  ['/game/hub88\\:hsg_mysterymotel', '/game/hacksaw:1071'],
  ['/game/hub88\\:hsg_forestfortune', '/game/hacksaw:1068'],
  ['/game/hub88\\:hsg_aztectwist', '/game/hacksaw:1066'],
  ['/game/hub88\\:hsg_frutz', '/game/hacksaw:1081'],
  ['/game/hub88\\:hsg_chaoscrewscratch', '/game/hacksaw:1092'],
  ['/game/hub88\\:hsg_xpander', '/game/hacksaw:1093'],
  ['/game/hub88\\:hsg_doublerainbow', '/game/hacksaw:1144'],
  ['/game/hub88\\:hsg_warriorways', '/game/hacksaw:1131'],
  ['/game/hub88\\:hsg_gladiatorlegends', '/game/hacksaw:1160'],
  ['/game/hub88\\:hsg_handofanubis', '/game/hacksaw:1164'],
  ['/game/hub88\\:hsg_timespinners', '/game/hacksaw:1181'],
  ['/game/hub88\\:hsg_dorkunit', '/game/hacksaw:1172'],
  ['/game/hub88\\:hsg_fruitduel', '/game/hacksaw:1197'],
  ['/game/hub88\\:hsg_alphaeagle', '/game/hacksaw:1201'],
  ['/game/hub88\\:hsg_loveisallyouneed', '/game/hacksaw:1072'],
  ['/game/hub88\\:hsg_footballscratch', '/game/hacksaw:1079'],
  ['/game/hub88\\:hsg_eggstracash', '/game/hacksaw:1082'],
  ['/game/hub88\\:hsg_theperfectscratch', '/game/hacksaw:1080'],
  ['/game/hub88\\:hsg_snowscratcher', '/game/hacksaw:1109'],
  ['/game/hub88\\:hsg_tigerscratch', '/game/hacksaw:1110'],
  ['/game/hub88\\:hsg_summerscratch', '/game/hacksaw:1180'],
  ['/game/slotegrator\\:sportsbook-1', '/sports'],
])

export const REDIRECTS: ReadonlyMap<string, string> = new Map([
  ...GAME_REDIRECTS,
  ['/slots', CASINO_SLOTS_LINK],
  ['/popular', CASINO_POPULAR_LINK],
  ['/gameshows', CASINO_GAME_SHOWS_LINK],
  ['/housegames', CASINO_ROOBET_GAMES_LINK],
  ['/blackjack', '/tag/blackjack'],
  ['/baccarat', '/tag/baccarat'],
  ['/drops-and-wins', '/tag/dropsandwins'],
  ['/livegames', '/tag/livegames'],
  ['group/*', '/tag/*'],
  ['/favorites', GAME_TAG_FAVORITES_LINK], // TODO remove when favorites are no longer handled as tags
  ['/tag/housegames', CASINO_ROOBET_GAMES_LINK],
])
