openapi: 3.0.3
info:
  title: Roobet Mines API
  description: |-
    In the Mines game, a player attempts to clear the gameboard successfully and progress without selecting a mine
    The user progresses through the minefield by selecting a tile
    - user selects tile
    - tile is a diamond, payout chances increases and requested to select a new tile
    - tile is a mine and wager is lost
    - user can cashout at any point after a tile has been selected

    Mines currently has fives difficulties
    - 1 Mine
    - 3 Mines
    - 5 Mines
    - 10 Mines
    - custom(N): N Mines

    Some useful links:
    - [Mines on Roobet](https://roobet.com/mines)
  version: 1.0.0
servers:
  - url: https://api.roobet.com
tags:
  - name: mines
    description: Mines API
paths:
  /mines/start:
    post:
      tags:
        - mines
      summary: Start a Mines game.
      description: This endpoint is called when a user starts a mines game. This starts the active game session and creates a bet record.
      operationId: startGame
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - clientSeed
                - amount
                - minesCount
              properties:
                clientSeed:
                  type: string
                  example: s33d3dgamesrcool
                amount:
                  type: number
                  example: 5
                minesCount:
                  type: number
                  example: 10
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MinesGame'
        '405':
          description: Invalid input
  /mines/cashout:
    post:
      tags:
        - mines
      summary: Cashout without progressing selecting a new game tile
      description: As long as the user has not "bombed" out, they can choose to cashout at any intermediate row and receive a payout based on our payout schedule.
      operationId: cashout
      parameters:
        - name: activeGameId
          in: query
          description: The id of the Mines game that is being played
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                bet:
                  $ref: '#/components/schemas/Bet'
                deck:
                  type: object
                  example: {0: "diamond", 1: "diamond", 2: "mine", 3: "diamond", 4: "diamond", 5: "diamond", 6: "diamond", 7: "diamond", 8: "diamond", 9: "mine", 10: "diamond", 11: "diamond", 12: "diamond", 13: "diamond", 14: "mine", 15: "diamond", 16: "diamond", 17: "diamond", 18: "diamond", 19: "diamond", 20: "diamond", 21: "diamond", 22: "diamond", 23: "diamond", 24: "diamond"}
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  bet:
                    $ref: '#/components/schemas/Bet'
        '405':
          description: Invalid input
  /mines/getActiveGame:
    get:
      tags:
        - mines
      summary: Fetches the user's currently active Mines game
      description: Users can only have one singleton active Mine game and this persists between sessions or page refreshes.
      operationId: getActiveGame
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  activeGameId:
                    type: string
                    format: uuid
                    example: 123e4567-e89b-12d3-a456-426614174000
                  bet:
                    $ref: '#/components/schemas/Bet'
                  provablyFairInfo:
                    $ref: '#/components/schemas/ProvablyFairInfo'
                  minesCount:
                    type: number
                    example: 3
                  multiplier:
                    type: number
                    example: 3.45
                  playedCards:
                    type: object
                    example: {5: "played", 10: "played", 11: "played"}
        '400':
          description: Invalid status value
  /mines/selectCard:
    post:
      tags:
        - mines
      summary: Select a tile in the active Mines gameboard
      description: The user can select a title only on the active board and will otherwise be rejected.
      operationId: selectCard
      parameters:
        - name: activeGameId
          in: query
          description: The id of the Mines game that is being played
          required: true
          schema:
            type: string
        - name: selectedCard
          in: query
          description: The row index of the card being selected
          required: true
          schema:
            type: integer
            minimum: 0
            maximum: 24
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  payoutMultiplier:
                    type: number
                    example: 2.0736
                  provablyFairInfo:
                    $ref: '#/components/schemas/ProvablyFairInfo'
                  result:
                    type: string
                    example: 'diamond'
        '400':
          description: Invalid status value
  /mines/selectMultipleCards:
    get:
      tags:
        - mines
      summary: Select multiple tile in the active Mines gameboard
      description: The user can select tiles only on the active board and will otherwise be rejected.
      operationId: selectMultipleCards
      parameters:
        - name: activeGameId
          in: query
          description: The id of the Mines game that is being played
          required: true
          schema:
            type: string
        - name: selectedCards
          in: query
          description: The selected cards to be played
          required: true
          schema:
            type: array
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  payoutMultiplier:
                    type: number
                    example: 2.0736
                  provablyFairInfo:
                    $ref: '#/components/schemas/ProvablyFairInfo'
                  result:
                    type: array
                    example: ['diamond', 'diamond', 'mine']
        '400':
          description: Invalid status value
components:
  schemas:
    MinesGame:
      type: object
      properties:
        activeGameId:
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000
        bet:
          $ref: '#/components/schemas/Bet'
        provablyFairInfo:
          $ref: '#/components/schemas/CurrentRoundProvablyFairInfo'
        game:
          $ref: '#/components/schemas/ActiveGame'
        minesCount:
          type: number
          example: 5
    ProvablyFairInfo:
      type: object
      properties:
        gameName:
          type: string
        nonce:
          type: number
        roundOver:
          type: boolean
        userId:
          type: string
          format: uuid
        hash:
          type: string
    CurrentRoundProvablyFairInfo:
      type: object
      properties:
        newRound:
          type: boolean
        currencRound:
          $ref: '#/components/schemas/ProvablyFairInfo'
        clientSeed:
          type: string
    Bet:
      type: object
      properties:
        balanceType:
          type: string
        betAmount:
          type: number
    ActiveGame:
      type: object
      properties:
        activeGameId:
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000
        bet:
          $ref: '#/components/schemas/Bet'
        provablyFairInfo:
          $ref: '#/components/schemas/CurrentRoundProvablyFairInfo'
    Difficulty:
      type: string
      enum:
        - 1
        - 3
        - 5
        - 10
        - custom
