const Hub88Providers = [
  'Booming Games',
  'Microgaming',
  'Blueprint Gaming',
  'Caleta Gaming',
  'Kalamba Games',
  'Habanero',
  'Green Jade',
  'Green Jade Arcade',
  'MrSlotty',
  'Evoplay Entertainment',
  'Fugaso',
  'EGT',
  'BetsyGames',
  'OneTouch',
  'Bombay Live',
  'Red Rake Gaming',
  'Gamomat',
  'Golden Rock Studios',
  'Endorphina',
  'Octoplay',
  'Rogue',
  'Genii',
  'LadyLuck',
  'Triple Edge',
  'Stormcraft',
  'Gameburger',
  'SpinPlay Games',
  'All41',
  'Alchemy Gaming',
  'JFTW',
  'Neon Valley',
  'Snowborn Studios',
  'Foxium',
  'Slingshot',
  'Northern Lights Gaming',
  'Buck Stakes Entertainment',
  'Old Skool',
  'Gong Gaming',
  'MG Slots',
  'MG Grand Live',
] as const
export type Hub88Provider = (typeof Hub88Providers)[number]
export const isHub88Provider = (value: any): value is Hub88Provider =>
  Hub88Providers.includes(value)
