export const examplePromoCodeData = [
  {
    claimAmount: '10',
    roowardsBonus: 'true',
    claimsRemaining: 10,
    expireTime: '5',
    code: 'test',
    balanceType: '',
    hasNotDeposited: 'false',
    mustBeAffiliated: 'false',
    depositCountAmount: 5,
    depositCountHours: 0,
    depositLimitAmount: 0,
    depositLimitHours: 0,
    wagerLimitAmount: 0,
    wagerLimitHours: 0,
    affiliateName: '',
  },
  {
    claimAmount: '15',
    roowardsBonus: 'false',
    claimsRemaining: 10,
    expireTime: '4',
    code: 'code',
    balanceType: 'ltc',
    hasNotDeposited: 'true',
    mustBeAffiliated: 'false',
    depositCountAmount: 0,
    depositCountHours: 0,
    depositLimitHours: 0,
    depositLimitAmount: 0,
    wagerLimitHours: 0,
    wagerLimitAmount: 0,
    affiliateName: '',
  },
  {
    claimAmount: '20',
    roowardsBonus: 'false',
    claimsRemaining: 10,
    expireTime: '3',
    code: 'promos',
    balanceType: 'eth',
    hasNotDeposited: 'false',
    mustBeAffiliated: 'true',
    depositCountAmount: 3,
    depositCountHours: 0,
    depositLimitAmount: 4,
    depositLimitHours: 0,
    wagerLimitAmount: 100,
    wagerLimitHours: 0,
    affiliateName: '',
  },
]
