export const examplePromoCodeData = [
  {
    claimAmount: '10',
    roowardsBonus: 'false',
    claimsRemaining: '10',
    expireTime: '3',
    code: 'DATA',
    balanceType: 'eth',
    hasNotDeposited: 'true',
    mustBeAffiliated: 'false',
    depositCountAmount: 0,
    depositCountHours: 0,
    depositLimitAmount: 0,
    depositLimitHours: 0,
    wagerLimitAmount: 0,
    wagerLimitHours: 0,
    affiliateName: '',
    cxAffId: '213',
  },
  {
    claimAmount: '10',
    roowardsBonus: 'true',
    claimsRemaining: '10',
    expireTime: 5,
    code: 'TEST',
    hasNotDeposited: 'false',
    mustBeAffiliated: 'false',
    depositCountAmount: 0,
    depositCountHours: 0,
    depositLimitAmount: 0,
    depositLimitHours: 0,
    wagerLimitAmount: 0,
    wagerLimitHours: 0,
    affiliateName: 'Tester',
    cxAffId: '',
  },
  {
    claimAmount: '15',
    roowardsBonus: 'false',
    claimsRemaining: '5',
    expireTime: 3,
    code: 'BULK',
    balanceType: 'ltc',
    hasNotDeposited: 'false',
    mustBeAffiliated: 'false',
    depositCountAmount: 5,
    depositCountHours: 0,
    depositLimitAmount: 5,
    depositLimitHours: 0,
    wagerLimitAmount: 5,
    wagerLimitHours: 0,
    affiliateName: '',
    cxAffId: '416',
  },
]
